"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { getLatestMarketAnalysis } from "./market-actions";

export type ContinuousMetric = { key: string; label: string; value: number | null; display: string };
export type ContinuousChange = { metric: string; previous: string; current: string; change: string; direction: "IMPROVING" | "STABLE" | "DECLINING" | "NEW" | "EVIDENCE UNAVAILABLE"; reason: string };
export type ContinuousReport = { module: "continuous"; title: string; report_type: "DAILY" | "WEEKLY" | "MONTHLY"; status: "COMPLETE"; generated_at: string; current: { metrics: ContinuousMetric[]; problems: string[]; opportunities: string[]; recommendations: string[]; sentiment: { positive: number | null; neutral: number | null; negative: number | null } }; previous: ContinuousReport["current"] | null; changes: ContinuousChange[]; what_improved: string[]; what_declined: string[]; what_stayed_stable: string[]; what_is_new: string[]; what_needs_attention: string[]; actions: { immediate: string[]; short_term: string[]; strategic: string[] }; evidence: string[] };
type Ctx = { supabase: Awaited<ReturnType<typeof createClient>>; user: { id: string }; product: Record<string, unknown>; market: Awaited<ReturnType<typeof getLatestMarketAnalysis>>; reports: Record<string, unknown>[] };
const text = (v: unknown): v is string => typeof v === "string" && v.trim().length > 0;
const list = (v: unknown): string[] => Array.isArray(v) ? v.filter(text) : [];
const num = (v: unknown) => typeof v === "number" && Number.isFinite(v) ? v : null;
async function context(productId: string): Promise<Ctx> { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error("You must be logged in."); const { data: product, error } = await supabase.from("products").select("*").eq("id", productId).eq("user_id", user.id).maybeSingle(); if (error || !product) throw new Error("Product not found."); const [market, reports] = await Promise.all([getLatestMarketAnalysis(productId), supabase.from("product_intelligence_reports").select("module,report,created_at").eq("product_id", productId).eq("user_id", user.id)]); return { supabase, user, product, market, reports: (reports.data || []).map((row) => ({ module: row.module, ...(row.report as Record<string, unknown>), created_at: row.created_at })) }; }
function currentSnapshot(ctx: Ctx) { const reports = ctx.reports; const performance = reports.find((r) => r.module === "performance"); const scalability = reports.find((r) => r.module === "scalability"); const review = reports.find((r) => r.module === "review" && !r.synthetic_test_data); const improvements = reports.find((r) => r.module === "improvements"); const suggestions = reports.find((r) => r.module === "suggestions"); const performanceScore = num(performance?.overall_score); const scalabilityScore = num(scalability?.score); const sentiment = (review?.sentiment_percentages || {}) as Record<string, unknown>; const metrics: ContinuousMetric[] = [{ key: "performance", label: "Performance score", value: performanceScore, display: performanceScore === null ? "EVIDENCE UNAVAILABLE" : `${performanceScore}/100` }, { key: "scalability", label: "Scalability score", value: scalabilityScore, display: scalabilityScore === null ? "EVIDENCE UNAVAILABLE" : `${scalabilityScore}/100` }, { key: "positive_sentiment", label: "Positive sentiment", value: num(sentiment.positive), display: num(sentiment.positive) === null ? "EVIDENCE UNAVAILABLE" : `${sentiment.positive}%` }, { key: "negative_sentiment", label: "Negative sentiment", value: num(sentiment.negative), display: num(sentiment.negative) === null ? "EVIDENCE UNAVAILABLE" : `${sentiment.negative}%` }]; const problems = list(review?.problems).concat(list(improvements?.failures).map((item) => typeof item === "object" && item ? String((item as Record<string, unknown>).title || "") : "").filter(Boolean)); const opportunities = list(scalability?.opportunities).concat(list(suggestions?.opportunities).map((item) => typeof item === "object" && item ? String((item as Record<string, unknown>).product_name || "") : "").filter(Boolean)); const recommendations = list(improvements?.prioritized_fixes).map((item) => typeof item === "object" && item ? String((item as Record<string, unknown>).title || "") : "").filter(Boolean).concat(list(scalability?.recommendations).map((item) => typeof item === "object" && item ? String((item as Record<string, unknown>).title || "") : "").filter(Boolean)); return { metrics, problems: [...new Set(problems)], opportunities: [...new Set(opportunities)], recommendations: [...new Set(recommendations)], sentiment: { positive: num(sentiment.positive), neutral: num(sentiment.neutral), negative: num(sentiment.negative) } }; }
function compare(previous: ContinuousReport["current"] | null, current: ContinuousReport["current"]): ContinuousChange[] { if (!previous) return []; return current.metrics.map((metric) => { const old = previous.metrics.find((item) => item.key === metric.key); if (!old || old.value === null || metric.value === null) return { metric: metric.label, previous: old?.display || "EVIDENCE UNAVAILABLE", current: metric.display, change: "EVIDENCE UNAVAILABLE", direction: "EVIDENCE UNAVAILABLE", reason: "Both comparable stored values are required." }; const delta = metric.value - old.value; const direction = Math.abs(delta) < 1 ? "STABLE" : (metric.key === "negative_sentiment" ? delta < 0 : delta > 0) ? "IMPROVING" : "DECLINING"; return { metric: metric.label, previous: old.display, current: metric.display, change: `${delta > 0 ? "+" : ""}${Math.round(delta * 10) / 10}`, direction, reason: "Compared with the previous saved Continuous Report snapshot." }; }); }
const added = (previous: string[] | undefined, current: string[]) => current.filter((item) => !(previous || []).includes(item));
export async function getContinuousReport(productId: string) { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return null; const { data } = await supabase.from("product_intelligence_reports").select("report").eq("product_id", productId).eq("user_id", user.id).eq("module", "continuous").maybeSingle(); return (data?.report as ContinuousReport | null) || null; }
export async function generateContinuousReport(productId: string, reportType: "DAILY" | "WEEKLY" | "MONTHLY") { const ctx = await context(productId); const saved = await getContinuousReport(productId); const current = currentSnapshot(ctx); const previous = saved?.current || null; const changes = compare(previous, current); const what_improved = changes.filter((item) => item.direction === "IMPROVING").map((item) => item.metric); const what_declined = changes.filter((item) => item.direction === "DECLINING").map((item) => item.metric); const what_stayed_stable = changes.filter((item) => item.direction === "STABLE").map((item) => item.metric); const what_is_new = [...added(previous?.problems, current.problems).map((item) => `New problem: ${item}`), ...added(previous?.opportunities, current.opportunities).map((item) => `New opportunity: ${item}`)]; const what_needs_attention = [...what_declined, ...current.problems.slice(0, 3)]; const report: ContinuousReport = { module: "continuous", title: `${reportType} CONTINUOUS REPORT`, report_type: reportType, status: "COMPLETE", generated_at: new Date().toISOString(), current, previous, changes, what_improved, what_declined, what_stayed_stable, what_is_new, what_needs_attention, actions: { immediate: what_needs_attention.length ? [`Review: ${what_needs_attention[0]}`] : ["Collect the next saved intelligence snapshot before prioritizing an immediate change."], short_term: current.opportunities.length ? [`Validate: ${current.opportunities[0]}`] : ["Collect additional opportunity evidence."], strategic: ["Maintain a manual report cadence and compare only stored snapshots."] }, evidence: [ctx.market.analysis ? "Saved Market Suggestion intelligence" : "MARKET EVIDENCE UNAVAILABLE", current.problems.length ? `${current.problems.length} stored problem signal(s)` : "PROBLEM HISTORY UNAVAILABLE", current.opportunities.length ? `${current.opportunities.length} stored opportunity signal(s)` : "OPPORTUNITY HISTORY UNAVAILABLE"] }; const { error } = await ctx.supabase.from("product_intelligence_reports").upsert({ user_id: ctx.user.id, product_id: productId, module: "continuous", report }, { onConflict: "user_id,product_id,module" }); if (error) throw new Error("Unable to save Continuous Report."); revalidatePath(`/dashboard/product/${productId}/continuous-reports`); return { report, status: "COMPLETE" as const, message: previous ? "COMPLETE" : "NO PREVIOUS REPORT AVAILABLE" }; }
