export type ReviewSourceType = "review" | "article" | "discussion" | "product page" | "competitor page" | "industry source";
export type ReviewResearchStatus = "AVAILABLE" | "NO_REVIEWS_FOUND" | "LIVE_REVIEW_RESEARCH_UNAVAILABLE";
export type LiveReviewSource = { title: string; url: string; domain: string; retrieved_at: string; published_at: string | null; source_type: ReviewSourceType; claim: string; evidence_text: string; is_quote: boolean };

type Citation = { url?: string; title?: string; start_index?: number; end_index?: number };
type GroundedPayload = { steps?: Array<{ type?: string; content?: Array<{ type?: string; text?: string; annotations?: Citation[] }> }> };

function clean(value: unknown) { return String(value || "").replace(/[()\"]/g, " ").replace(/\s+/g, " ").trim().slice(0, 120); }
function domainFor(url: string) { try { return new URL(url).hostname.replace(/^www\./, ""); } catch { return "unknown"; } }
function sourceType(url: string, title: string): ReviewSourceType { const value = `${url} ${title}`.toLowerCase(); if (/reddit|forum|discussion|community/.test(value)) return "discussion"; if (/flipkart|amazon|retailer|shop|store|rating|verified.?buyer|customer.?review/.test(value)) return "review"; if (/review|hands.?on|verdict|pros.?and.?cons/.test(value)) return "article"; if (/compare|competitor/.test(value)) return "competitor page"; return "industry source"; }

function productQueries(productName: string, category: string) { const name = clean(productName); const suffix = category ? ` ${clean(category)}` : ""; return [`${name} customer reviews`, `${name} user reviews`, `${name} verified buyer reviews`, `${name} problems`, `${name} complaints`, `${name} user experience`, `${name} review`, `${name} Reddit`, `${name} Flipkart reviews`, `${name} Amazon reviews`, `${name} expert review`, `${name} long term review${suffix}`]; }

function groundedSources(payload: GroundedPayload, productName: string): LiveReviewSource[] { const now = new Date().toISOString(); const output: LiveReviewSource[] = []; const seen = new Set<string>(); for (const step of payload.steps || []) { if (step.type !== "model_output") continue; for (const block of step.content || []) { if (block.type !== "text" || !block.text) continue; for (const annotation of block.annotations || []) { const url = annotation.url?.trim(); if (!url || !/^https?:\/\//i.test(url) || /(^|\.)google\./i.test(domainFor(url)) || seen.has(url)) continue; const start = Number.isInteger(annotation.start_index) ? annotation.start_index as number : 0; const end = Number.isInteger(annotation.end_index) ? annotation.end_index as number : block.text.length; const excerpt = block.text.slice(Math.max(0, start), Math.min(block.text.length, end)).trim().slice(0, 700); const title = String(annotation.title || domainFor(url)).trim(); if (!excerpt && !title) continue; seen.add(url); output.push({ title, url, domain: domainFor(url), retrieved_at: now, published_at: null, source_type: sourceType(url, title), claim: excerpt ? `Grounded evidence from ${title}: ${excerpt}` : `Grounded source for ${productName}: ${title}`, evidence_text: excerpt || title, is_quote: false }); } } } return output.slice(0, 24); }

export async function researchLiveReviews(product: Record<string, unknown>) { const key = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY; const name = clean(product.name); const category = clean(product.category); if (!key) return { status: "LIVE_REVIEW_RESEARCH_UNAVAILABLE" as const, sources: [] as LiveReviewSource[], failed_sources: 0, error: "GEMINI_API_KEY is not configured on the server." }; if (!name) return { status: "LIVE_REVIEW_RESEARCH_UNAVAILABLE" as const, sources: [] as LiveReviewSource[], failed_sources: 0, error: "The saved product has no name." };
  const prompt = `Research the saved product ${name} using Google Search grounding. Run multiple searches covering: ${productQueries(name, category).map((query) => `"${query}"`).join(", ")}. Find real customer reviews, verified-buyer or retailer feedback, expert reviews, public Reddit/user discussions, and complaint or problem discussions when available. Return a concise evidence-bound review research summary. Do not invent reviews, ratings, counts, quotes, dates, URLs, or statistics. Every factual statement must be supported by a grounded web citation.`;
  try { const response = await fetch("https://generativelanguage.googleapis.com/v1beta/interactions", { method: "POST", headers: { "content-type": "application/json", "x-goog-api-key": key }, body: JSON.stringify({ model: "gemini-3.6-flash", input: prompt, tools: [{ type: "google_search" }] }), cache: "no-store" }); if (!response.ok) { const detail = (await response.text()).slice(0, 300).replace(/\s+/g, " ").trim(); return { status: "LIVE_REVIEW_RESEARCH_UNAVAILABLE" as const, sources: [] as LiveReviewSource[], failed_sources: 0, error: `Gemini Google Search returned HTTP ${response.status}${detail ? `: ${detail}` : "."}` }; } const payload = await response.json() as GroundedPayload; const sources = groundedSources(payload, name); if (sources.length < 3) return { status: "NO_REVIEWS_FOUND" as const, sources: [] as LiveReviewSource[], failed_sources: sources.length, error: `Grounded response contained only ${sources.length} usable cited sources.` }; return { status: "AVAILABLE" as const, sources, failed_sources: 0 }; } catch (error) { return { status: "LIVE_REVIEW_RESEARCH_UNAVAILABLE" as const, sources: [] as LiveReviewSource[], failed_sources: 0, error: error instanceof Error ? `Gemini request failed: ${error.message}` : "Gemini request failed." }; }
}
